services:
  web:
    build: .
    restart: unless-stopped
    env_file: .env
    networks:
      - database_network
    ports:
      - "${PORT}:8000"

networks:
  database_network:
    external: true
    name: ${DATABASE_NETWORK}
