# Generated by Django 6.0.7 on 2026-08-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds.', null=True)),
                ('status', models.CharField(db_index=True, max_length=10)),
                ('in_24_hours', models.BooleanField(default=False)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('rated_range', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(blank=True, default='', max_length=20)),
                ('is_rated', models.CharField(blank=True, default='', max_length=5)),
                ('is_official', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='LastUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
